feat: added level start event
kyranet/drakhtar-telemetry pull request #3
Opened 2021-04-29 15:42 UTC by Acedpol

2021-04-29 21:12 UTC, kyranet reviewed
One question, doesn't the new event type be added in the tracker's accept method?

2021-04-29 21:12 UTC, kyranet commented on include/TrackerEvents/HitPointsArmyEvent.h
> +};
Missing EOF:
```suggestion
};

```

2021-04-29 21:12 UTC, kyranet commented on src/TrackerEvents/HitPointArmyEvent.cpp
> +}
Missing EOF:
```suggestion
}

```

2021-04-30 10:41 UTC, onaranjoUCM requested changes
Los nombres no son intuitivos, se supone que este evento indica cuándo un batallón ha perdido vida, "army" se entiende como el ejército entero y "hitPoints" no me dice nada. Sugiero simplemente "AttackEvent". 

Además, según el documento el evento necesita recoger el tipo de la unidad atacante y defensora además de la cantidad de daño hecho.

2021-04-30 10:45 UTC, onaranjoUCM commented
> One question, doesn't the new event type be added in the tracker's accept method?

Yes, but the current tracker (PlayTracker) is a placeholder. There is a TODO to make a "DrakhtarTraker" that includes all the new events and removes old ones.

2021-05-05 14:00 UTC, onaranjoUCM approved these changes

2021-05-05 14:02 UTC, kyranet approved these changes

2021-05-05 14:04 UTC, merged